name: Terraform Manual Workflow

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Branch to use for Terraform code'
        required: true
        default: 'main'
        run_apply:
          description: 'Do you want to run terraform apply? (true/false)'
          required: true
          default: 'false'

jobs:
  terraform:
    name: Run Terraform Commands
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.source_branch }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

      # Uncomment below if you want to apply changes too
      - name: Terraform Apply
        if: ${{ github.event.inputs.run_apply == 'true' }}
        run: terraform apply -auto-approve
