name: Terraform Manual Workflow

on:
  workflow_dispatch:  

jobs:
  terraform:
    name: Run Terraform Commands
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

      # Uncomment below if you want to apply changes too
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
